"""JSON rows → output/sql/codex.sql (schema + INSERTs, SQLite and PostgreSQL)."""

from __future__ import annotations

from pathlib import Path


def _lit(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def _insert(table: str, row: dict) -> str:
    cols = ", ".join(row)
    vals = ", ".join(_lit(v) for v in row.values())
    return f"INSERT INTO {table} ({cols}) VALUES ({vals});"


def to_sql(data: dict[str, list], schema_sql: str) -> str:
    out = [
        "-- Generated by `uv run codex-data extract`. Do not edit by hand.",
        "BEGIN;",
        schema_sql.strip(),
        "",
    ]
    for s in data["sections"]:
        out.append(_insert("section", {
            "id": s["id"], "title": s["title"], "position": s["position"], "start_page": s["startPage"],
        }))
    for c in data["clubs"]:
        out.append(_insert("club", {
            "id": c["id"],
            "name": c["name"],
            "motto": c["motto"],
            "description": c["description"],
            "founded": c["founded"],
            "founders": ", ".join(c["founders"]) or None,
            "colours": "–".join(c["colours"]) or None,
        }))
    for s in data["songs"]:
        out.append(_insert("song", {
            "id": s["id"],
            "title": s["title"],
            "sort_title": s["sortTitle"],
            "section_id": s["section"],
            "language": s["language"],
            "club_id": s["clubId"],
            "page_start": s["pages"]["start"],
            "page_end": s["pages"]["end"],
            "lyricist": s["lyricist"],
            "melody": s["melody"],
            "notes": s["notes"],
        }))
        for i, st in enumerate(s["stanzas"]):
            out.append(_insert("stanza", {
                "song_id": s["id"],
                "position": i,
                "kind": st["kind"],
                "repeat": st.get("repeat", 1),
                "instruction": st.get("instruction"),
            }))
            for j, text in enumerate(st.get("lines", [])):
                out.append(_insert("line", {
                    "song_id": s["id"], "stanza_position": i, "position": j, "text": text,
                }))
            for r in st.get("repeats", []):
                out.append(_insert("repeat_span", {
                    "song_id": s["id"],
                    "stanza_position": i,
                    "from_line": r["from"],
                    "to_line": r["to"],
                    "times": r.get("times"),
                    "marker": r["marker"],
                }))
    out.append("COMMIT;")
    return "\n".join(out) + "\n"


def write_sql(data: dict[str, list], schema_path: Path, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "codex.sql").write_text(to_sql(data, schema_path.read_text()), encoding="utf-8")
